version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    patterns: ["*"]
    commit-message:
      prefix: "[#16] "
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    # Only security updates for Cargo
    open-pull-requests-limit: 0
  - package-ecosystem: "bazel"
    directory: "/"
    patterns: ["*"]
    commit-message:
      prefix: "[#16] "
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    # Only security updates for Bazel
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directories: 
      - "/iceoryx2-ffi/python"
      - "/doc/api/python"
    patterns: ["*"]
    commit-message:
      prefix: "[#16] "
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    # Only security updates for Pip
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions"
    patterns: ["*"]
    commit-message:
      prefix: "[#16] "
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    # Only security updates for GitHub Actions
    open-pull-requests-limit: 0
