version: 2

updates:
  - package-ecosystem: "cargo"
    directories: 
      - "/"
      - "/integrations/ros2"
      - "/integrations/zenoh"
    patterns: ["*"]
    commit-message:
      prefix: "[#16]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "bazel"
    directory: "/"
    patterns: ["*"]
    commit-message:
      prefix: "[#16]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "pip"
    directories: 
      - "/iceoryx2-ffi/python"
      - "/doc/api/python"
    patterns: ["*"]
    commit-message:
      prefix: "[#16]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions"
    patterns: ["*"]
    commit-message:
      prefix: "[#16]"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
