name: Release

on:
  workflow_dispatch:

jobs:
  build-python-wheels:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest          # aarch64
          - windows-latest
    defaults:
      run:
        shell: bash               # required for windows

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # version v6.0.2

      - name: Set Up Python & Install Poetry
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # version: v6.0.1
        with:
          python-version: "3.13"
      - run: pip install poetry==2.2.1

      - name: Install Global Plugins # (needed for windows due to separate C:\ and D:\ drives)
        if: runner.os == 'Windows'
        run: poetry self add "poethepoet[poetry-plugin]>=0.35.0,<0.36.0"

      - name: Build Wheel
        run: |
          poetry --project iceoryx2-ffi/python install
          poetry --project iceoryx2-ffi/python build-wheel

      - name: Upload Wheel
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # version: v7.0.0
        with:
          name: wheels-${{ runner.os }}-${{ runner.arch }}-${{ github.sha }}
          path: target/ff/python/dist
          retention-days: 7

  prepare-python-dist:
    needs: [build-python-wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # version v6.0.2

      - name: Set Up Python & Install Poetry
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # version: v6.0.1
        with:
          python-version: "3.13"
      - run: pip install poetry==2.2.1

      - name: Download Wheels
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # version: v8.0.0
        with:
          pattern: wheels-*-${{ github.sha }}
          path: dist
          merge-multiple: true

      - name: Build source distribution
        run: |
          # Build
          poetry --project iceoryx2-ffi/python install
          poetry --project iceoryx2-ffi/python build-sdist

          cp target/ff/python/dist/*.tar.gz dist/
          
          # Validate
          echo "Validating wheels..."
          if ls dist/*.whl 1> /dev/null 2>&1; then
            poetry --project iceoryx2-ffi/python run twine check dist/*.whl
          else
            echo "No wheel files to validate"
          fi

      - name: Upload Distribution
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # version: v7.0.0
        with:
          name: python-dist-${{ github.sha }}
          path: dist/
          retention-days: 7

      - name: Display distribution summary
        run: |
          echo "Generated Python dist with contents:"
          for file in dist/*; do
            if [ -f "$file" ]; then
              echo "$(basename "$file"): $(stat -c%s "$file") bytes"
            fi
          done
